name: dp
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pillow
  - tifffile
  - zarr
  - imagecodecs
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - pip:
      - umap-learn
